### ISSUE TITLE
Make sidebar "what can I make" open filter view in new page

### ISSUE THREAD

**Issue by sirtastic** [entrity/tipsy-web-public#40]
Currently pops above drink page if you are viewing a drink. Have it populate a blank page.

![image](https://cloud.githubusercontent.com/assets/3707868/9052616/9024011a-3a1e-11e5-9a48-29469db56281.png)

**Comment by entrity** [comment]
@sirtastic :

1. This isn't a bug. It was intentional.
2. Change it? What if the result is paltry? IMO, the current design is *way* better! (And it provides results sooner b/c it requires no page reload. And it can be closed immediately to resume what the user was checking out before.)

I made a change, though: try it now (starting this pm after I push some more commits), and you'll see it scroll you to an appropriate position.

If that's still not enough for you, let's talk by voice or get a population of user testers to check it out and share their preferences.

**Comment by sirtastic** [comment]
It's very unusual UX.  I can think of no examples of this behavior in the wild (on the web) and it will throw people off.  We will resolve any paltry lists with **"recommendations"** (eg: We can't display any drinks because none match this criteria, but don't dismay! If you had cranberry juice you could make these drinks: ..., or if you had orange juice you could make these drinks: ...)

The real crux of this app (i think) will be its sweet recommendations and that should take center stage.

**Comment by entrity** [comment]
@sirtastic : would you open a ticket where you spell out the logic for the drink suggestions? The question to answer is:

> How do I know what drinks should be considered suggestions or related drinks (for "What can I make?" and the "related drinks" at the bottom of the drinks page)?

**Comment by entrity** [comment]
commit 150ed91bc7baecd801b9b19c0a1de84cfdfd5b68
Date:   Wed Aug 5 15:30:29 2015 -0700

    Hide main content when finder.ingredients is not empty. Resolves #40 (github)
