### ISSUE TITLE
Make comments scroll to comments section + comment count

### ISSUE THREAD

**Issue by sirtastic** [entrity/tipsy-web-public#67]
Tried using an anchor/hash but it didn't work. Currently comment count is not reflecting actual comments number.

![image](https://cloud.githubusercontent.com/assets/3707868/9401409/c96531fc-4783-11e5-98f0-ccc62e441849.png)

**Comment by entrity** [comment]
@sirtastic : with these changes:

1. creation of new comments will increment the drink's comment count
1. you can run `rake drink:count_comments` to update your db to have correct comment counts for your pre-existing comments
1. to create links that go to anchors (e.g. `#comments`), instead of `href='#comments'` use `ng-click="gotoFrag('comments')"`

commit 1bac932fc79ef1a384406dc8e238dbdcfbffed9d
Date:   Fri Aug 21 15:45:20 2015 -0700

    Add rake task for counting drink comments. Fixes #67 (github)

commit 9b9c396897deca0c3c37e70298498fcb847a0091
Date:   Fri Aug 21 15:42:40 2015 -0700

    Add fn for navigating to fragment. Fixes #67 (github)

commit 00abc58b5887ead02b0a2ccf9a6539d527bcc0f2
Date:   Fri Aug 21 15:38:04 2015 -0700

    Increment drink comment_ct on comments#create. Fixes #67 (github)
