### ISSUE TITLE
Make actions direct non-logged in users to registration page (not login modal)

### ISSUE THREAD

**Issue by sirtastic** [entrity/tipsy-web-public#77]
@entrity  The login modal you built doesn't work on my android phone for some reason. The buttons don't respond to clicks, possibly z-index weirdness?  If you don't have time to troubleshoot it please change the code to point users to the login page.

Make all the commenting actions (reply, like, dislike, tip, etc) send the user to the login page (or fixed modal) as well.

**Comment by entrity** [comment]
Fixed touch events for mobile. (The problem was caused by `ngTouch` directive. I put in a hack, including an attr `stop-event="touchend"` on top-level elem inside modal. There's also a directive `stopEvent`, which I pulled from https://github.com/angular-ui/bootstrap/issues/2017#issuecomment-39515923).

In summary: still using the modal, but the touch events should work now.

commit 26f085ab5917fc533054c918e4695f7ba42e2d41
Date:   Wed Aug 26 10:00:04 2015 -0700

    Fix touch events in modals (w/ stopEvent) directive. Fixes #77 (github)

**Comment by sirtastic** [comment]
@entrity Re-opening because adding ingredients to fridge/shopping list is still possible while logged out (not sure what it's doing but its toggling the icons to active and not spawning a login modal).

**Comment by entrity** [comment]
Why wouldn't it be okay to have a fridge/shopping list regardless of whether you're logged in? My understanding was that these features don't change our data, so you don't need a login. Seems a shame to deprive users of a useful feature which costs us nothing to share.
