### ISSUE TITLE
Scotty we need more power!  - SuperDuperUser Status

### ISSUE THREAD

**Issue by sirtastic** [entrity/tipsy-web-public#97]
SSH just isn't going to cut it in the long run.

![image](https://cloud.githubusercontent.com/assets/3707868/9771978/51c0db0e-56ee-11e5-9fbe-d504ff85e922.png)

**Comment by entrity** [comment]
@sirtastic : got a functional (read 'not pretty') admin page(s) set up. To access it, you need to have 1000+ points.

1. SSH in as user `apache` (not yourself so that you have access to db etc)
1. `cd` into project directory and execute (substituting your user id or someone else's for where I have written `3`): `rails r 'User.find(3).update_attributes(points:1001)'`
1. In browser, navigate to https://tipsyology.com/admin/revisions . (Check out the categorical hyperlinks at the top of the content.)
1. Poke around. See what you can do.

commit 68bdeaa88a4efb606e0f48defc0bb0c1bb31c07b
Date:   Sat Oct 3 21:20:43 2015 -0700

    Add crude admin views at /admin/revisions etc. To access this, user must have at least 1000 points. Closes #97
